#ifndef _parallelogram_H_
#define _parallelogram_H_

enum
{
	PY_PARALLELOGRAMOBJECT_EDGE_A  	   = 1000,
	PY_PARALLELOGRAMOBJECT_EDGE_B  	   = 1001,
	PY_PARALLELOGRAMOBJECT_SUB_A   	   = 1002,
	PY_PARALLELOGRAMOBJECT_SUB_B   	   = 1003,
	PY_PARALLELOGRAMOBJECT_HEIGHT  	   = 1004,
	PY_PARALLELOGRAMOBJECT_ANGLE   	   = 1005,
	PY_PARALLELOGRAMOBJECT_KEEP      = 1006,
	_DUMMY_ELEMENT_
};

#endif