CONTAINER parallelogram
{
	NAME parallelogram;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL 	PY_PARALLELOGRAMOBJECT_EDGE_A			{ UNIT METER; MIN 0.0; }
		REAL 	PY_PARALLELOGRAMOBJECT_EDGE_B			{ UNIT METER; MIN 0.0; }
		LONG 	PY_PARALLELOGRAMOBJECT_SUB_A			{ MIN 1; MAX 1000; }
		LONG 	PY_PARALLELOGRAMOBJECT_SUB_B			{ MIN 1; MAX 1000; }
		REAL 	PY_PARALLELOGRAMOBJECT_HEIGHT			{ UNIT METER; MIN 0.0; }
		REAL 	PY_PARALLELOGRAMOBJECT_ANGLE			{ UNIT DEGREE; MIN 0.0; MAX 180.0; }
		BOOL	PY_PARALLELOGRAMOBJECT_KEEP				{ ; }
	}
	
	INCLUDE Oprimitiveaxis;
}
